In [16]:
import string
import numpy as np
import pandas as pd

In [17]:
#proof of conc...
samples = ['samuel', 'bryan', 'samantha']
character = string.printable #all printable ascii character
token_index = dict(zip(range(1, len(character) + 1), character)) #builds index of all tokens in data

max_length = 50 #Vectorizes samples, only consider the first max_length values in the sample
results = np.zeros((len(samples), max_length, max(token_index.keys())+1))
for i, sample in enumerate(samples):
    for j, character in enumerate(sample):
        index = token_index.get(character)
        results[i, j, index] = 1


In [18]:
print(results)
print(len(token_index))

[[[1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]]
100


In [70]:
from keras import preprocessing
train_data = 'embed_train.csv'
test_data = 'embed_test.csv'


max_features = 10000
max_length = 18


In [71]:
df = pd.read_csv(train_data)
df.columns = ['fname','lname','dob','passwd','fnameAgg','lnameAgg','dobAgg','percent_sim']
df.head()


fname      lname         dob     passwd  fnameAgg  lnameAgg  dobAgg  \
0  Chris  McConnell  0000-00-00     vivmcc    18.182    13.333   0.000   
1   John  McConnell  0000-00-00    sense12    18.182    25.000   0.000   
2    Koy      Kragh  1977-03-02     harf42     0.000    18.182  12.500   
3   João    Marques  1978-06-13  jotaX7820    15.385    12.500  31.579   
4  KTEST      KTEST  1969-01-10     harf42     0.000     0.000   0.000   

  percent_sim  
0      10.505  
1      14.394  
2      10.227  
3      19.821  
4         0.0

In [72]:
df2 = pd.read_csv(test_data)
df2.columns = ['fname','lname','dob','passwd','fnameAgg','lnameAgg','dobAgg','percent_sim']
df2.head()

fname          lname         dob      passwd  fnameAgg  lnameAgg  dobAgg  \
0   Martin  Calatrava Bol  1972-02-24      011111     0.000     0.000  12.500   
1      A R       KARTHICK  1979-07-19   winner19k     0.000     0.000  21.053   
2     greg       jeffries  1986-07-24     fresh69    36.364    53.333  11.765   
3   Stasia       Polashak  1978-05-25    homefree     0.000    12.500   0.000   
4  William       Nancolas  1956-07-09  stockcar#8    11.765    11.111   0.000   

   percent_sim  
0        4.167  
1        7.018  
2       33.821  
3        4.167  
4        7.625

In [76]:
#creating xtrain and ytrain
sample1 = df['fname']
sample2 = df['lname']
sample3 = df['dob']
y_sample = df['percent_sim']
ytrain = []

for i in y_sample:
    if float(i.strip('s')) < 30.0:
        ytrain.append(0.0)
    else:
        ytrain.append(1.0)

#creating xtest and ytest       
sample1_test = df['fname']
sample2_test = df['lname']
sample3_test = df['dob']
ytest_sample = df['percent_sim']
ytest = []

for i in ytest_sample:
    if float(i.strip('s')) < 30.0:
        ytest.append(0.0)
    else:
        ytest.append(1.0)
        

max_length = 50 #Can be any length we choose

#this is the function I am using to encode and it returns an array of the encoded letters
def encode_function(samples):
    results = np.zeros((len(samples), max_length, max(token_index.keys())+1))
    for i, sample in enumerate(samples):
        for j, character in enumerate(sample):
            index = token_index.get(character)
            results[i, j, index] = 1
    return results

In [79]:
#creates the arrays for each category

fname = encode_function(sample1)
lname = encode_function(sample2)
dob = encode_function(sample3)

#creating the training data where xtrain is the 2d array of each category
#and ytrain is supposed to be either 0/1 but it's midnight and I am going to stop here

xtrain = [fname,lname,dob]

In [94]:
#creates the arrays for each category for testing

fname_test = encode_function(sample1_test)
lname_test = encode_function(sample2_test)
dob_test = encode_function(sample3_test)

#creating the training data where xtest is the 2d array of each category
#and ytrain is supposed to be either 0/1 but it's midnight and I am going to stop here

xtest = [fname,lname]
#print(xtest)
print(fname)

[[[1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 ...

 [[1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]]


In [81]:
preprocessing.sequence.pad_sequences(xtrain, maxlen=max_length)
preprocessing.sequence.pad_sequences(xtest, maxlen=max_length)

array([[[[1, 1, 1, ..., 1, 1, 1],
         [1, 1, 1, ..., 1, 1, 1],
         [1, 1, 1, ..., 1, 1, 1],
         ...,
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0]],

        [[1, 1, 1, ..., 1, 1, 1],
         [1, 1, 1, ..., 1, 1, 1],
         [1, 1, 1, ..., 1, 1, 1],
         ...,
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0]],

        [[1, 1, 1, ..., 1, 1, 1],
         [1, 1, 1, ..., 1, 1, 1],
         [1, 1, 1, ..., 1, 1, 1],
         ...,
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0]],

        ...,

        [[1, 1, 1, ..., 1, 1, 1],
         [1, 1, 1, ..., 1, 1, 1],
         [1, 1, 1, ..., 1, 1, 1],
         ...,
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0]],

        [[1, 1, 1, ..., 1, 1, 1],
         [1, 1, 1, ..., 1, 1, 1],
         [1, 1, 1, ..., 1, 1, 1],
    

In [93]:
from keras.models import Sequential
from keras.layers import Flatten, Dense, Embedding

model = Sequential()
model.add(Embedding(10000, 8, input_length=max_length))

model.add(Flatten())

model.add(Dense(1, activation='sigmoid'))
model.compile(optimizer='rmsprop', loss='binary_crossentropy', metrics=['acc'])
model.summary()

history = model.fit(fname, ytrain, epochs=10, batch_size=32, validation_split=0.2)

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_6 (Embedding)      (None, 50, 8)             80000     
_________________________________________________________________
flatten_6 (Flatten)          (None, 400)               0         
_________________________________________________________________
dense_6 (Dense)              (None, 1)                 401       
Total params: 80,401
Trainable params: 80,401
Non-trainable params: 0
_________________________________________________________________


ValueError: Error when checking input: expected embedding_6_input to have 2 dimensions, but got array with shape (249, 50, 101)