In [16]:
import string
import numpy as np
import pandas as pd

In [17]:
#proof of conc...
samples = ['samuel', 'bryan', 'samantha']
character = string.printable #all printable ascii character
token_index = dict(zip(range(1, len(character) + 1), character)) #builds index of all tokens in data

max_length = 50 #Vectorizes samples, only consider the first max_length values in the sample
results = np.zeros((len(samples), max_length, max(token_index.keys())+1))
for i, sample in enumerate(samples):
    for j, character in enumerate(sample):
        index = token_index.get(character)
        results[i, j, index] = 1


In [18]:
print(results)
print(len(token_index))

[[[1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]]
100


In [19]:
from keras import preprocessing
train_data = 'embed_train.csv'
test_data = 'embed_train.csv'


max_features = 10000
max_length = 18


In [28]:
df = pd.read_csv(train_data)
df.columns = ['fname','lname','dob','passwd','fnameAgg','lnameAgg','dobAgg','percent_sim']
df.head()

fname      lname         dob     passwd  fnameAgg  lnameAgg  dobAgg  \
0  Chris  McConnell  0000-00-00     vivmcc    18.182    13.333   0.000   
1   John  McConnell  0000-00-00    sense12    18.182    25.000   0.000   
2    Koy      Kragh  1977-03-02     harf42     0.000    18.182  12.500   
3   João    Marques  1978-06-13  jotaX7820    15.385    12.500  31.579   
4  KTEST      KTEST  1969-01-10     harf42     0.000     0.000   0.000   

  percent_sim  
0      10.505  
1      14.394  
2      10.227  
3      19.821  
4         0.0

In [39]:
sample1 = df['fname']
sample2 = df['lname']
sample3 = df['dob']
y_sample = df['percent_sim']

max_length = 50 #Can be any length we choose

#this is the function I am using to encode and it returns an array of the encoded letters
def encode_function(samples):
    results = np.zeros((len(samples), max_length, max(token_index.keys())+1))
    for i, sample in enumerate(samples):
        for j, character in enumerate(sample):
            index = token_index.get(character)
            results[i, j, index] = 1
    return results

In [41]:
#creates the arrays for each category

fname = encode_function(sample1)
lname = encode_function(sample2)
dob = encode_function(sample3)

#creating the training data where xtrain is the 2d array of each category
#and ytrain is supposed to be either 0/1 but it's midnight and I am going to stop here

xtrain = [fname,lname,dob]
ytrain = encode_function(y_sample)